//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft_Flight
    {
        public long flight_id { get; set; }
        public long aircraft_id { get; set; }
        public int AFRef { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
