//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftSeating
    {
        public long aircraft_id { get; set; }
        public long seat_id { get; set; }
        public int class_id { get; set; }
        public int SeatRef { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual SeatingPrice SeatingPrice { get; set; }
        public virtual TravelClass TravelClass { get; set; }
    }
}
