//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatingPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatingPrice()
        {
            this.AircraftSeatings = new HashSet<AircraftSeating>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public long seat_id { get; set; }
        public long flight_id { get; set; }
        public long aircraft_id { get; set; }
        public decimal price_bit { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AircraftSeating> AircraftSeatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
